### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MartialBE** [MartialBE/one-api#132]
- [ ] 完善用户删除/重新注册的问题
- [ ] 允许用户自定义剩余多少余额发送邮件通知
- [ ] 增加消息推送，可以推送到TG/钉钉等
- [ ] 完善消息推送种类，例如每日总结/渠道失败通知等等
- [ ] 耗时统计 由秒 改为 完成TOKEN/时间 得到 xx t/s 能更精确体现速度
- [ ] 完善Redis， 可以记录错误次数，错误渠道，错误代码等等
- [ ] 增加中转cache机制 (是管理员启用还是每个用户可以启用?)
- [ ] 支付
- [ ] 分组重构，可以为分组设置 速率/升级机制(充值满足多少自动升级分组)
